name: jarvis_assistant
description: Suhana AI Assistant
publish_to: "none"
version: 2.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_tts: ^4.0.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
