name: jarvis_assistant
description: Suhana AI Assistant
publish_to: 'none'
version: 2.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  http: ^1.2.0
  flutter_tts: 3.8.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
